name: build Mi-Assistant

on:
  workflow_dispatch:

env:
  VERSION: 1.1

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: gcc -o miasst_linux64 main.c libs/*.c -Llibs/linux -lusb-1.0 -lcurl

      - name: Upload Release Asset (Linux)
        run: |
          gh release upload ${{ env.VERSION }} ./miasst_linux64 --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y mingw-w64
      - run: i686-w64-mingw32-gcc -o miasst_windows_32.exe main.c libs/*.c -Llibs/windows_32 -lusb-1.0 -lcurl
      - run: x86_64-w64-mingw32-gcc -o miasst_windows_64.exe main.c libs/*.c -Llibs/windows_64 -lusb-1.0 -lcurl

      - name: Upload Release Assets (Windows)
        run: |
          cp ./libs/windows_32/libcurl.dll .
          zip -r miasst_windows_32.zip libcurl.dll miasst_windows_32.exe
          cp ./libs/windows_64/libcurl-x64.dll .
          zip -r miasst_windows_64.zip libcurl-x64.dll miasst_windows_64.exe
          gh release upload ${{ env.VERSION }} ./miasst_windows_32.zip ./miasst_windows_64.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}


  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: gcc -o miasst_macos64 main.c libs/*.c -Llibs/macos -lusb-1.0 -lcurl

      - name: Upload Release Asset (macOS)
        run: |
          gh release upload ${{ env.VERSION }} ./miasst_macos64 --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}


  termux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: /usr/local/lib/android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang -o miasst_termux_aarch64 main.c libs/*.c -Llibs/termux_aarch64 -Wl,-rpath=/data/data/com.termux/files/usr/lib/ -lusb-1.0 -lcurl

      - run: /usr/local/lib/android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi30-clang -o miasst_termux_arm main.c libs/*.c -Llibs/termux_arm -Wl,-rpath=/data/data/com.termux/files/usr/lib/ -lusb-1.0 -lcurl

      - name: Upload Release Assets (termux)
        run: |
          gh release upload ${{ env.VERSION }} ./miasst_termux_arm ./miasst_termux_aarch64 --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}





