name: Build with Clang

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - run: |
          CLANG_PATH=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin
          echo "Clang path: $CLANG_PATH"
          ls $CLANG_PATH
          find $CLANG_PATH -name '*clang*'
          $CLANG_PATH/aarch64-linux-android33-clang -o miasst main.c libs/*.c -Llibs/termux_aarch64 -lusb-1.0 -lcurl -Wl,-rpath=/data/data/com.termux/files/usr/lib/