name: Build with Clang

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Build
        run: |
          CLANG_PATH=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin
          $CLANG_PATH/aarch64-linux-android30-clang -o miasst main.c libs/*.c -Llibs/termux_aarch64 -Wl,-rpath=/data/data/com.termux/files/usr/lib/ -Wl,-rpath-link=libs/termux_aarch64 -lusb-1.0 -lcurl -I/data/data/com.termux/files/home/test/data/data/com.termux/files/usr/lib/clang/18/include/llvm_libc_wrappers/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: miasst
          path: miasst